import '@/styles/globals.css'

export const metadata = {
  title: 'Create CK App',
  description: 'Generated by ck-cli',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
